// 示範／種子資料。
// 過往活動清單整理自內部試算表，僅過濾出「小遊戲性質」的活動（排除純造型上架、許願池等非遊戲活動）。
// 設計目的（拉新/回流/留存...）與成效數據多數尚待營運團隊補齊，先以空值 / 待補充呈現，
// 待正式串接 Google Sheet 後，可直接在 Sheet 或「新增活動紀錄」表單中補上真實數據。
// images 為活動照片連結陣列，目前皆為空陣列（尚未收集照片），之後可直接在 Sheet 的 images 欄位貼上圖片連結（一行一個）。

const MOCK_ACTIVITIES = [
  {
    id: 'seed_01', name: '小遊戲挑戰送元流睡衣套裝', dateText: '2026/06/18 10:00–06/30 23:59',
    dateStart: '2026-06-18', dateEnd: '2026-06-30',
    description: '完成小遊戲挑戰可獲得甜夢時光套裝（元流 7011、7012）。',
    mechanism: '2048 玩法，透過合併方塊累積分數達成關卡目標。',
    mechanismTags: ['益智消除'], purposeTags: [], specialTags: [], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_02', name: '源寶旅行日記', dateText: '2026/01/30 14:00–02/06 23:59',
    dateStart: '2026-01-30', dateEnd: '2026-02-06',
    description: '',
    mechanism: '玩家可進行「源寶旅行日記」創作，完成日記後累積進度並獲得對應獎勵。',
    mechanismTags: ['任務養成'], purposeTags: [], specialTags: [], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_03', name: '宮中一夢 × 請安大作戰', dateText: '2026/02/19 14:00–03/18 23:59',
    dateStart: '2026-02-19', dateEnd: '2026-03-18',
    description: '完成聯動劇情任務可獲得聯動語音、回城特效、加速特效等聯動獎勵。',
    mechanism: '向皇上大聲請安，並躲過其他嬪妃的阻撓，考驗反應速度。',
    mechanismTags: ['反應操作'], purposeTags: [], specialTags: ['IP聯動'], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_04', name: '新年祈福光明燈', dateText: '2025/01/24 16:00–02/03 23:59',
    dateStart: '2025-01-24', dateEnd: '2025-02-03',
    description: '',
    mechanism: '點擊各燈下方「去點燈」按鈕查看任務列表，完成任務累積福氣值（鈔能力燈可直接投入金幣點燈）。',
    mechanismTags: ['任務養成'], purposeTags: [], specialTags: ['節慶檔期'], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_05', name: '女僕甜點店', dateText: '2025/02/20 16:00–03/09 23:59',
    dateStart: '2025-02-20', dateEnd: '2025-03-09',
    description: '下發羊咩女僕頭像（valorpass9022）。',
    mechanism: '經營甜點店拿好禮！完成任務解鎖餐點種類，上架並獲取收益，兌換里程碑獎勵。',
    mechanismTags: ['經營模擬'], purposeTags: [], specialTags: [], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_06', name: '我要成為咒術師', dateText: '2025/03/28 14:00–04/19 23:59',
    dateStart: '2025-03-28', dateEnd: '2025-04-19',
    description: '完成任務可得「吵死人了」永久表情。',
    mechanism: '式神大出擊：丟青蛙／爆打咒靈館：打地鼠／咒術電影院：觀影達指定時長領取禮包，開啟有機會獲得限時造型抵用券。',
    mechanismTags: ['反應操作'], purposeTags: [], specialTags: ['IP聯動'], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_07', name: '夏日酥脆挑戰賽', dateText: '2025/06/14 12:00–06/30 23:59',
    dateStart: '2025-06-14', dateEnd: '2025-06-30',
    description: '酥脆特派員造型（53008）。',
    mechanism: '摳糖餅、木頭人等反應類小遊戲玩法。',
    mechanismTags: ['反應操作'], purposeTags: [], specialTags: ['節慶檔期'], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_08', name: '貓蟲鑑定送永久表情', dateText: '2025/09/05 14:00–09/21 23:59',
    dateStart: '2025-09-05', dateEnd: '2025-09-21',
    description: '完成測驗送永久表情。',
    mechanism: '心理測驗形式，依作答結果分派鑑定結果。',
    mechanismTags: ['心理測驗'], purposeTags: [], specialTags: [], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_09', name: '紫苑食堂送週邊', dateText: '2025/11/14 14:00–11/30 23:59',
    dateStart: '2025-11-14', dateEnd: '2025-11-30',
    description: '完成任務送實體週邊。',
    mechanism: '紫苑的料理日記：找出食材的完美比例。',
    mechanismTags: ['經營模擬', '益智消除'], purposeTags: [], specialTags: [], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_10', name: '新年新希望！挑戰拿獎勵！', dateText: '2025/12/27 14:00–2026/02/08 23:59',
    dateStart: '2025-12-27', dateEnd: '2026-02-08',
    description: '（新年）時光膠囊。',
    mechanism: '跨年檔期任務累積型玩法，開啟時光膠囊獲得獎勵。',
    mechanismTags: ['任務養成'], purposeTags: [], specialTags: ['節慶檔期'], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_11', name: '戰慄的龍卷', dateText: '2024/4/2 14:00–4/30 23:59',
    dateStart: '2024-04-02', dateEnd: '2024-04-30',
    description: '大獎造型「戰慄的龍卷-克里希」（10611，附贈相框382）。',
    mechanism: '每次應援可獲得 5～25 個應援棒，不同對手及戰鬥結果獲得不同數量，累積應援棒達標可獲得聯動獎勵及大獎。',
    mechanismTags: ['陣營競賽', '任務養成'], purposeTags: [], specialTags: ['IP聯動'], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_12', name: '星願季一番賞', dateText: '2024/4/3 14:00–4/14 23:59',
    dateStart: '2024-04-03', dateEnd: '2024-04-14',
    description: '',
    mechanism: '完成指定任務即可免費獲得抽獎券參與抽獎。',
    mechanismTags: ['抽獎機率'], purposeTags: [], specialTags: [], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_13', name: '安奈特的夏日冰坊', dateText: '2024/6/19 10:00–7/7 23:59',
    dateStart: '2024-06-19', dateEnd: '2024-07-07',
    description: '里程碑大獎「安奈特-蜜雪澄心」造型（51911）。',
    mechanism: '經營冰鋪拿好禮！完成任務解鎖新冰淇淋種類，上架獲取收益，兌換里程碑獎勵。',
    mechanismTags: ['經營模擬'], purposeTags: [], specialTags: ['節慶檔期'], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_14', name: '屬於我的2024傳說', dateText: '2024/7/6–7/8',
    dateStart: '2024-07-06', dateEnd: '2024-07-08',
    description: '開箱必得指定名單造型其中之一，或機會升級進階寶箱。',
    mechanism: '玩家進入活動頁面回顧年度傳說大事記與個人數據，完成回顧後獲得年度回顧驚喜箱。',
    mechanismTags: ['劇情回顧'], purposeTags: [], specialTags: ['週年慶'], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_15', name: '艾森諾攻防戰', dateText: '2024/9/18 16:00–10/6 23:59',
    dateStart: '2024-09-18', dateEnd: '2024-10-06',
    description: '四大陣營冠軍相框（帶限時前綴「最強」）。',
    mechanism: '玩家選擇陣營加入，透過每日任務累積「小兵」派遣攻擊領土，依領土佔領結算「戰功」，總結算依陣營戰功排序給予對應獎勵。',
    mechanismTags: ['陣營競賽'], purposeTags: [], specialTags: [], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_16', name: '咒力輸出挑戰', dateText: '2024/11/1 14:00–11/17 23:59',
    dateStart: '2024-11-01', dateEnd: '2024-11-17',
    description: '完成積分挑戰送限定表情。',
    mechanism: '拚手速點擊累積咒力，累積達標完成積分挑戰。',
    mechanismTags: ['反應操作'], purposeTags: [], specialTags: ['IP聯動'], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_17', name: '新年活躍 H5', dateText: '2023/1/17–1/31',
    dateStart: '2023-01-17', dateEnd: '2023-01-31',
    description: '解鎖所有場景可領取最終大獎造型五選一。',
    mechanism: '透過指定任務獲得茶點，消耗茶點探索新年奇境，共六個場景。',
    mechanismTags: ['任務養成', '劇情回顧'], purposeTags: [], specialTags: ['節慶檔期'], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_18', name: '回歸之路 由我指引', dateText: '2023/12/6 16:00–12/20 23:59',
    dateStart: '2023-12-06', dateEnd: '2023-12-20',
    description: '積分達標可領取星河徽章、紫色卷軸等好禮。',
    mechanism: '進入活動網頁後顯示個人積分累積頁面，透過指定方式獲取積分。',
    mechanismTags: ['任務養成'], purposeTags: ['回流'], specialTags: ['老玩家回歸'], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_19', name: '分享H5 建造大作戰', dateText: '2023/4/10 16:00–4/27 23:59',
    dateStart: '2023-04-10', dateEnd: '2023-04-27',
    description: '英雄造型五選一。',
    mechanism: '玩遊戲領沙子，用沙子蓋沙堡，可邀請朋友一起捍衛沙堡。',
    mechanismTags: ['社交邀請'], purposeTags: ['拉新'], specialTags: [], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_20', name: 'H5 點亮傳說燈火', dateText: '2023/7/7 16:00–7/18 23:59',
    dateStart: '2023-07-07', dateEnd: '2023-07-18',
    description: '',
    mechanism: '完成任務點亮所在區域。',
    mechanismTags: ['任務養成'], purposeTags: [], specialTags: ['週年慶'], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_21', name: '傳說紀念冊', dateText: '2023/7/10 16:00–7/18 23:59',
    dateStart: '2023-07-10', dateEnd: '2023-07-18',
    description: '',
    mechanism: '進入傳說紀念冊活動可觀看年度回顧，並領取個人專屬獎勵。',
    mechanismTags: ['劇情回顧'], purposeTags: [], specialTags: ['週年慶'], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_22', name: '摯友の合奏', dateText: '2023/7/15 16:00–8/14 23:59',
    dateStart: '2023-07-15', dateEnd: '2023-08-14',
    description: '',
    mechanism: '活動頁面選擇 1 個喜歡的獎勵，完成任務獲得幫助次數，輸入邀請碼幫助好朋友合奏，成功後免費獲得所選獎勵。',
    mechanismTags: ['社交邀請'], purposeTags: ['留存', '拉新'], specialTags: [], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_23', name: '心理測驗 H5', dateText: '2023/10/19–11/1',
    dateStart: '2023-10-19', dateEnd: '2023-11-01',
    description: '下發 S-Dreamer 相框（huodong_HeadFrame406）。',
    mechanism: '心理測驗形式。',
    mechanismTags: ['心理測驗'], purposeTags: [], specialTags: [], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_24', name: 'H5 凡恩發紅包', dateText: '2023/1/14–2/3',
    dateStart: '2023-01-14', dateEnd: '2023-02-03',
    description: '',
    mechanism: '跟朋友互送發財金，兌換造型。',
    mechanismTags: ['社交邀請'], purposeTags: [], specialTags: ['節慶檔期'], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_25', name: '誰是你的幸運女神', dateText: '2023/3/25 00:00–4/6 23:59',
    dateStart: '2023-03-25', dateEnd: '2023-04-06',
    description: '資源上架：艾瑞的比心（41322）。',
    mechanism: '心理測驗形式。',
    mechanismTags: ['心理測驗'], purposeTags: [], specialTags: [], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_26', name: 'H5 嘉年華樂園', dateText: '2023/4/29–5/14',
    dateStart: '2023-04-29', dateEnd: '2023-05-14',
    description: '',
    mechanism: '射箭、打地鼠、放映廳等多款小遊戲合輯。',
    mechanismTags: ['反應操作'], purposeTags: [], specialTags: [], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_27', name: '傳說日音樂同樂會', dateText: '2023/7/13 16:00–7/26 23:59',
    dateStart: '2023-07-13', dateEnd: '2023-07-26',
    description: '英雄五選一選擇卡（祖卡、綺蘿、拉茲、奎倫、銀晝）。',
    mechanism: '登入完成任務獲得能量，利用能量解鎖音樂關卡，共 12 關，關卡難度對應獎勵。',
    mechanismTags: ['音樂節奏'], purposeTags: [], specialTags: ['週年慶'], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_28', name: '挑戰 X 念 X 測驗', dateText: '2023/8/1–8/20',
    dateStart: '2023-08-01', dateEnd: '2023-08-20',
    description: '完成測驗送西索表情（永久）。',
    mechanism: '念能力測試（心理測驗形式）。',
    mechanismTags: ['心理測驗'], purposeTags: [], specialTags: ['IP聯動'], metrics: null,
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
];

// 活動靈感範例資料，方便預覽介面外觀；正式使用時可直接從畫面上刪除或保留給團隊參考。
const MOCK_IDEAS = [
  {
    id: 'idea_seed_01',
    title: '「傳說占卜屋」——用玩家戰績生成專屬運勢卡',
    description: '串接玩家近期對戰數據，生成一張趣味「本週運勢卡」（例如：MVP運、打野運、躲塔運），並附上對應的小任務，完成任務可兌換造型碎片。結合心理測驗的低門檻與個人化戰績的話題性。',
    submittedBy: '陳曉雯',
    purposeTags: ['留存', '品牌口碑'],
    specialTags: ['低開發成本'],
    inspirationRef: '心理測驗 H5',
    createdAt: '2026-05-12T09:00:00.000Z',
  },
  {
    id: 'idea_seed_02',
    title: '回歸玩家限定「老朋友地圖」',
    description: '針對久未登入的玩家，用一張「回憶地圖」呈現他們過去常用英雄與高光時刻，沿途完成任務逐步解鎖獎勵，最終召喚一位老朋友（好友系統）一起開局可獲得雙倍獎勵。',
    submittedBy: '林柏宇',
    purposeTags: ['回流'],
    specialTags: ['老玩家回歸'],
    inspirationRef: '回歸之路 由我指引',
    createdAt: '2026-05-20T09:00:00.000Z',
  },
  {
    id: 'idea_seed_03',
    title: '暑假限定「電競選手打工日記」',
    description: '結合暑假檔期與電競賽事熱度，玩家體驗「選手一日打工」小遊戲（訓練、採訪、比賽三關卡），完成後可獲得選手周邊造型與賽事門票抽獎資格。',
    submittedBy: '黃紫涵',
    purposeTags: ['拉新', '品牌口碑'],
    specialTags: ['電競賽事聯動', '節慶檔期'],
    inspirationRef: '',
    createdAt: '2026-06-02T09:00:00.000Z',
  },
];
