// 示範／種子資料。
// 過往活動清單整理自內部試算表，僅過濾出「小遊戲性質」的活動（排除純造型上架、許願池等非遊戲活動）。
// 設計目的（拉新/回流/留存...）與成效數據多數尚待營運團隊補齊，先以空值 / 待補充呈現，
// 待正式串接 Google Sheet 後，可直接在 Sheet 或「新增活動紀錄」表單中補上真實數據。
// images 為活動照片連結陣列，目前皆為空陣列（尚未收集照片），之後可直接在 Sheet 的 images 欄位貼上圖片連結（一行一個）。
// activityType：H5活動 / 遊戲內活動，遊戲內活動泛指活動中心、換皮、序號、聊天彩蛋、快捷語音等各種形式的條件兌換型活動。

const MOCK_ACTIVITIES = [
  {
    id: 'seed_01', name: '小遊戲挑戰送元流睡衣套裝', dateText: '2026/06/18 10:00–06/30 23:59',
    dateStart: '2026-06-18', dateEnd: '2026-06-30',
    activityType: 'H5活動',
    description: '完成小遊戲挑戰可獲得甜夢時光套裝（元流 7011、7012）。',
    mechanism: '2048 玩法，透過合併方塊累積分數達成關卡目標。',
    mechanismTags: ['益智消除'], purposeTags: ['提升非對局在線時長'], specialTags: [],
    metrics: { visitRate: 11.62, completionRate: 1.48 },
    referenceLink: '', images: ['過往活動圖/小遊戲挑戰送元流睡衣套裝（2048）.jpg'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_02', name: '源寶旅行日記', dateText: '2026/01/30 14:00–02/06 23:59',
    dateStart: '2026-01-30', dateEnd: '2026-02-06',
    activityType: 'H5活動',
    description: '',
    mechanism: '玩家可進行「源寶旅行日記」創作，完成日記後累積進度並獲得對應獎勵。',
    mechanismTags: ['任務養成'], purposeTags: ['提升非對局在線時長'], specialTags: [],
    metrics: { visitRate: 34.38, completionRate: 12.24 },
    referenceLink: '', images: ['https://kgtw-cdn-garenanow-com-sh.obs.cn-east-3.myhuaweicloud.com/mgames/kgtw/events/mj/2026/1/YuanbaosDiarypop2.png'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_03', name: '宮中一夢', dateText: '2026/02/17 10:00–03/18 23:59',
    dateStart: '2026-02-17', dateEnd: '2026-03-18',
    activityType: 'H5活動',
    description: '甄嬔聯動周邊：凌雲峰加速（加速）、臣妾做不到你表情（表情）、你的福氣在後頭（回城）。',
    mechanism: '向皇上大聲請安，並躲過其他嬪妃的阻撓，考驗反應速度。',
    mechanismTags: ['劇情回顧'], purposeTags: [], specialTags: ['IP聯動'],
    metrics: { visitRate: 21.57, completionRate: 4.24 },
    referenceLink: '', images: ['過往活動圖/宮中一夢.jpg'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_04', name: '新年祈福光明燈', dateText: '2025/01/24 16:00–02/03 23:59',
    dateStart: '2025-01-24', dateEnd: '2025-02-03',
    activityType: 'H5活動',
    description: '',
    mechanism: '點擊各燈下方「去點燈」按鈕查看任務列表，完成任務累積福氣值（鈔能力燈可直接投入金幣點燈）。',
    mechanismTags: ['任務養成'], purposeTags: ['提升非對局在線時長'], specialTags: ['節慶檔期'],
    metrics: { visitRate: 28.23, completionRate: 19.40 },
    referenceLink: '', images: ['https://kgtw.cdn.garenanow.com/mgames/kgtw/events/candle/2501/%E6%8B%8D%E8%87%89.png'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_05', name: '女僕甜點店', dateText: '2025/02/20 16:00–03/09 23:59',
    dateStart: '2025-02-20', dateEnd: '2025-03-09',
    activityType: 'H5活動',
    description: '下發羊咩女僕頭像（valorpass9022）。',
    mechanism: '經營甜點店拿好禮！完成任務解鎖餐點種類，上架並獲取收益，兌換里程碑獎勵。',
    mechanismTags: ['經營模擬'], purposeTags: ['提升非對局在線時長'], specialTags: [],
    metrics: { visitRate: 30.08, completionRate: 7.89 },
    referenceLink: '', images: ['過往活動圖/女僕甜點店.jpg'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_07', name: '夏日酥脆挑戰賽', dateText: '2025/06/14 12:00–06/30 23:59',
    dateStart: '2025-06-14', dateEnd: '2025-06-30',
    activityType: 'H5活動',
    description: '酥脆特派員造型（53008）。',
    mechanism: '摳糖餅、木頭人等反應類小遊戲玩法。',
    mechanismTags: ['反應操作'], purposeTags: ['提升非對局在線時長'], specialTags: ['節慶檔期'],
    metrics: { visitRate: 53.83, completionRate: 8.15 },
    referenceLink: '', images: ['https://p2.bahamut.com.tw/B/2KU/28/a52f823cd8e4a2b216a52cb7061uimc5.JPG'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_08', name: '貓蟲鑑定送永久表情', dateText: '2025/09/05 14:00–09/21 23:59',
    dateStart: '2025-09-05', dateEnd: '2025-09-21',
    activityType: 'H5活動',
    description: '完成測驗送永久表情。',
    mechanism: '心理測驗形式，依作答結果分派鑑定結果。',
    mechanismTags: ['心理測驗'], purposeTags: ['提升非對局在線時長'], specialTags: [],
    metrics: { visitRate: 42.35, completionRate: 32.64 },
    referenceLink: '', images: ['過往活動圖/貓蟲鑑定送永久表情.jpg'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_13', name: '安奈特的夏日冰坊', dateText: '2024/6/19 10:00–7/7 23:59',
    dateStart: '2024-06-19', dateEnd: '2024-07-07',
    activityType: 'H5活動',
    description: '里程碑大獎「安奈特-蜜雪澄心」造型（51911）。',
    mechanism: '經營冰鋪拿好禮！完成任務解鎖新冰淇淋種類，上架獲取收益，兌換里程碑獎勵。',
    mechanismTags: ['經營模擬'], purposeTags: ['提升非對局在線時長'], specialTags: ['節慶檔期'],
    metrics: { visitRate: 31.14, completionRate: 8.79 },
    referenceLink: '', images: ['過往活動圖/安奈特的夏日冰坊.jpg'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_14', name: '屬於我的2024傳說', dateText: '2024/7/6–7/8',
    dateStart: '2024-07-06', dateEnd: '2024-07-08',
    activityType: 'H5活動',
    description: '開箱必得指定名單造型其中之一，或機會升級進階寶箱。',
    mechanism: '玩家進入活動頁面回顧年度傳說大事記與個人數據，完成回顧後獲得年度回顧驚喜箱。',
    mechanismTags: ['劇情回顧'], purposeTags: ['提升非對局在線時長'], specialTags: ['週年慶'],
    metrics: { visitRate: 48.57, completionRate: 48.24 },
    referenceLink: '', images: ['過往活動圖/屬於我的2024傳說 (1).jpg'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_15', name: '艾森諾攻防戰', dateText: '2024/9/18 16:00–10/6 23:59',
    dateStart: '2024-09-18', dateEnd: '2024-10-06',
    activityType: 'H5活動',
    description: '四大陣營冠軍相框（帶限時前綴「最強」）。',
    mechanism: '玩家選擇陣營加入，透過每日任務累積「小兵」派遣攻擊領土，依領土佔領結算「戰功」，總結算依陣營戰功排序給予對應獎勵。',
    mechanismTags: ['陣營競賽'], purposeTags: ['提升非對局在線時長'], specialTags: [],
    metrics: { visitRate: 23.25, completionRate: 4.93 },
    referenceLink: '', images: ['https://kgtw.cdn.garenanow.com/mgames/kgtw/events/officalweb/0918.png'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_16', name: '咒力輸出挑戰', dateText: '2024/11/1 14:00–11/17 23:59',
    dateStart: '2024-11-01', dateEnd: '2024-11-17',
    activityType: 'H5活動',
    description: '完成積分挑戰送限定表情。',
    mechanism: '拚手速點擊累積咒力，累積達標完成積分挑戰。',
    mechanismTags: ['反應操作'], purposeTags: ['提升非對局在線時長'], specialTags: ['IP聯動'],
    metrics: { visitRate: 30.68, completionRate: 10.78 },
    referenceLink: '', images: ['過往活動圖/咒力輸出挑戰.jpg'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_25', name: '誰是你的幸運女神', dateText: '2023/3/25 00:00–4/6 23:59',
    dateStart: '2023-03-25', dateEnd: '2023-04-06',
    activityType: 'H5活動',
    description: '資源上架：艾瑞的比心（41322）。',
    mechanism: '心理測驗形式。',
    mechanismTags: ['心理測驗'], purposeTags: ['提升非對局在線時長'], specialTags: [], metrics: null,
    referenceLink: '', images: ['過往活動圖/誰是你的幸運女神.jpg'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_26', name: '嘉年華樂園', dateText: '2023/4/29–5/14',
    dateStart: '2023-04-29', dateEnd: '2023-05-14',
    activityType: 'H5活動',
    description: '',
    mechanism: '射箭、打地鼠、放映廳等多款小遊戲合輯。',
    mechanismTags: ['反應操作'], purposeTags: ['提升非對局在線時長'], specialTags: [], metrics: null,
    referenceLink: '', images: ['過往活動圖/H5 嘉年華樂園.jpg'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_29', name: '週年慶回憶錄', dateText: '2024/10/25 17:00–10/28 23:59',
    dateStart: '2024-10-25', dateEnd: '2024-10-28',
    activityType: 'H5活動',
    description: '完成回顧任務可獲得「週年玩家稱號」。',
    mechanism: '',
    mechanismTags: [], purposeTags: ['提升非對局在線時長'], specialTags: ['週年慶'],
    metrics: { visitRate: 43.97, completionRate: 27.48 },
    referenceLink: '', images: [], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_30', name: '源寶洗澡', dateText: '2026/04/20–05/10',
    dateStart: '2026-04-20', dateEnd: '2026-05-10',
    activityType: 'H5活動',
    description: '完成任務可獲得 MEN\'s Biore 同城裝飾（永久）。',
    mechanism: '「源寶的洗澡日常」，透過洗澡卡與源寶培養親密度，獲得 MEN\'s Biore 聯名回城特效等獎勵。',
    mechanismTags: [], purposeTags: ['提升非對局在線時長'], specialTags: [],
    metrics: { visitRate: 20.17, completionRate: 8.63 },
    referenceLink: '', images: ['https://cdn.yesmedia.com.tw/wp-content/uploads/2026/04/20260408170227_45-scaled.jpg'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_31', name: '在一起，強大！（情人節哥布林活動）', dateText: '2025/02/14',
    dateStart: '2025-02-14', dateEnd: '2025-02-14',
    activityType: '遊戲內活動',
    description: '大獎：哥布林相框。時事哏：哥布林 & 英雄諧音。',
    mechanism: '活動中心條件兌換，完成指定條件即可兌換哥布林相框。',
    mechanismTags: [], purposeTags: [], specialTags: ['時事熱點'],
    metrics: { visitRate: 72.65, completionRate: 23.65 },
    referenceLink: '', images: ['熱點活動圖/哥布林拍臉套圖.jpg'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_32', name: '四宮格ilua 跟著羊咩去遶境', dateText: '2025/04/03',
    dateStart: '2025-04-03', dateEnd: '2025-04-03',
    activityType: '遊戲內活動',
    description: '大獎：羊咩遶境相框。玩法哏：擲筊、尋找威力（尋找羊咩）。',
    mechanism: 'ilua（換皮）活動，四宮格互動形式兌換獎勵。',
    mechanismTags: [], purposeTags: [], specialTags: ['時事熱點'],
    metrics: { visitRate: 69.98, completionRate: 28.60 },
    referenceLink: '', images: ['熱點活動圖/大甲四宮格ilua-主頁.jpg'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_33', name: '粽教大戰爭', dateText: '2025/05/19',
    dateStart: '2025-05-19', dateEnd: '2025-05-19',
    activityType: '遊戲內活動',
    description: '大獎：造型自選箱。時事哏：戰南北粽（南北粽之爭）。',
    mechanism: '條件兌換活動，完成指定條件兌換造型自選箱。',
    mechanismTags: [], purposeTags: [], specialTags: ['時事熱點'],
    metrics: { visitRate: 65.20, completionRate: 3.67 },
    referenceLink: '', images: ['熱點活動圖/粽教大戰爭.jpg'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_34', name: '版更登入領 Chill Guy 頭像（寶藏男孩比洛爾登場）', dateText: '2025/01/08',
    dateStart: '2025-01-08', dateEnd: '2025-01-08',
    activityType: '遊戲內活動',
    description: '大獎：弗Chill倫頭像。時事哏：Chill Guy 梗。',
    mechanism: '聊天彩蛋形式，版本更新後登入即可領取。',
    mechanismTags: [], purposeTags: [], specialTags: ['時事熱點'],
    metrics: { visitRate: 7.49, completionRate: 7.49 },
    referenceLink: '', images: ['熱點活動圖/登入領 Chill guy.jpg'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_35', name: '蕭煌奇盲盒', dateText: '2025/07/26',
    dateStart: '2025-07-26', dateEnd: '2025-07-26',
    activityType: '遊戲內活動',
    description: '大獎：趣味頭像（眼前的黑不是黑、你說的白是什麼白、真的白、真的黑、超7凱恩）。時事哏：蕭煌奇梗。',
    mechanism: '序號兌換形式，輸入序號兌換趣味頭像。',
    mechanismTags: [], purposeTags: [], specialTags: ['時事熱點'],
    metrics: { visitRate: 20.27, completionRate: 20.27 },
    referenceLink: '', images: ['熱點活動圖/蕭煌奇盲盒.jpg'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_36', name: '尼克星語音表情／快捷語音', dateText: '2026/03/28',
    dateStart: '2026-03-28', dateEnd: '2026-03-28',
    activityType: '遊戲內活動',
    description: '大獎：「不要生漆」語音表情 41591。時事哏：尼克星 & 0322 梗。',
    mechanism: '快捷語音形式，觸發指定條件兌換語音表情。',
    mechanismTags: [], purposeTags: [], specialTags: ['時事熱點'],
    metrics: { visitRate: 60.43, completionRate: 60.43 },
    referenceLink: '', images: ['熱點活動圖/尼克星語音表情_快捷語音.jpg'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_37', name: '我的刀盾（頭像／頭框／加星卡）', dateText: '2026/05/20',
    dateStart: '2026-05-20', dateEnd: '2026-05-20',
    activityType: '遊戲內活動',
    description: '大獎：我的刀盾頭像。時事哏：刀盾。',
    mechanism: '活動中心條件兌換，完成指定條件兌換頭像／頭框／加星卡。',
    mechanismTags: [], purposeTags: [], specialTags: ['時事熱點'],
    metrics: { visitRate: 63.06, completionRate: 26.37 },
    referenceLink: '', images: ['熱點活動圖/我的刀盾 (頭像_頭框_加星卡).jpg'], createdBy: '歷史活動彙整',
  },
  {
    id: 'seed_38', name: '67 領限時點劵＆拉回流', dateText: '2026/06/04',
    dateStart: '2026-06-04', dateEnd: '2026-06-04',
    activityType: '遊戲內活動',
    description: '大獎：710 限時點劵。時事哏：67。備註：邀請＆被邀累積約 9 萬人。',
    mechanism: '活動中心拉回流模板＋條件兌換，邀請好友互動兌換限時點劵。',
    mechanismTags: [], purposeTags: [], specialTags: ['時事熱點', '老玩家回歸'],
    metrics: null,
    referenceLink: '', images: ['熱點活動圖/01. [67 回來啦]：拍臉.jpg'], createdBy: '歷史活動彙整',
  },
];

// 活動靈感範例資料（H5 活動靈感 + 熱點活動靈感合併在同一個靈感庫，用 ideaType 區分）。
// 方便預覽介面外觀；正式使用時可直接從畫面上刪除或保留給團隊參考。
const MOCK_IDEAS = [
  {
    id: 'idea_seed_01',
    ideaType: 'h5',
    title: '「傳說占卜屋」——用玩家戰績生成專屬運勢卡',
    description: '串接玩家近期對戰數據，生成一張趣味「本週運勢卡」（例如：MVP運、打野運、躲塔運），並附上對應的小任務，完成任務可兌換造型碎片。結合心理測驗的低門檻與個人化戰績的話題性。',
    submittedBy: '陳曉雯',
    images: [],
    demoUrl: '',
    topicRef: '',
    attachments: [],
    purposeTags: ['提升非對局在線時長', '提升登入率'],
    inspirationRef: '貓蟲鑑定送永久表情',
    likes: 0,
    comments: [],
    createdAt: '2026-05-12T09:00:00.000Z',
  },
  {
    id: 'idea_seed_02',
    ideaType: 'h5',
    title: '回歸玩家限定「老朋友地圖」',
    description: '針對久未登入的玩家，用一張「回憶地圖」呈現他們過去常用英雄與高光時刻，沿途完成任務逐步解鎖獎勵，最終召喚一位老朋友（好友系統）一起開局可獲得雙倍獎勵。',
    submittedBy: '林柏宇',
    images: [],
    demoUrl: '',
    topicRef: '',
    attachments: [],
    purposeTags: ['提升主要模式時長'],
    inspirationRef: '',
    likes: 0,
    comments: [],
    createdAt: '2026-05-20T09:00:00.000Z',
  },
  {
    id: 'idea_seed_03',
    ideaType: 'hotspot',
    title: '暑假限定「電競選手打工日記」',
    description: '結合暑假檔期與電競賽事熱度，玩家體驗「選手一日打工」小遊戲（訓練、採訪、比賽三關卡），完成後可獲得選手周邊造型與賽事門票抽獎資格。',
    submittedBy: '黃紫涵',
    images: [],
    demoUrl: '',
    topicRef: '暑假電競賽事熱潮',
    attachments: [],
    purposeTags: ['提升其他模式時長'],
    inspirationRef: '',
    likes: 0,
    comments: [],
    createdAt: '2026-06-02T09:00:00.000Z',
  },
];
